package com.whois.endpoints.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-07-13T18:46:43.142-03:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://soap.endpoints.whois.com/", name = "ISoapWhoisService")
@XmlSeeAlso({ObjectFactory.class})
public interface ISoapWhoisService {

    @WebMethod
    @RequestWrapper(localName = "check", targetNamespace = "http://soap.endpoints.whois.com/", className = "com.whois.endpoints.soap.Check")
    @ResponseWrapper(localName = "checkResponse", targetNamespace = "http://soap.endpoints.whois.com/", className = "com.whois.endpoints.soap.CheckResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.whois.endpoints.soap.SoapWhoisResponse check(

        @WebParam(name = "whois11", targetNamespace = "")
        com.whois.endpoints.soap.SoapWhoisRequest whois11
    );
}
